service: talents
app: intera-case
org: thiagoslomski
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
functions:
  app-intera-talent-api:
    handler: handler.handler
    events: 
      - http:
          path: /
          method: get
          cors: true
      - http: 
          path: /{proxy+}
          method: any
          cors: true